final List<String> allPrompts = [
  "Shadows at Play",
  "A Pop of Red",
  "Morning Routine",
  "Reflections",
  "The Golden Hour",
  "Urban Jungle",
  "Through a Window",
  "Symmetry",
  "Textures",
  "Motion in Stillness",
  "Street Art",
  "Monochrome Moment",
  "Contrasting Colors",
  "Tiny Details",
  "Lost in the Crowd",
  "Patterns in Chaos",
  "Unusual Perspective",
  "Parallel Lines",
  "A Touch of Green",
  "Hidden Gem",
  "Vintage Vibes",
  "Nature's Art",
  "Rust & Decay",
  "Minimalist Composition",
  "Food for Thought",
  "Color Explosion",
  "Lines & Curves",
  "Unexpected Pairing",
  "In the Mirror",
  "The Quiet Place",
];
